<?xml version="1.0"?>
<package format="2">
  <name>yaets</name>
  <version>0.0.1</version>
  <description>This package provides an execution tracing library.</description>
  <maintainer email="fmrico@gmail.com">Francisco Martín Rico</maintainer>
  <license>Apache License, Version 2.0</license>

  <!-- Build dependencies -->
  <build_depend>catkin</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <!-- Test dependencies -->
  <test_depend>rostest</test_depend>

  <export>
    <!-- Export information for ROS1 -->
    <catkin />
  </export>
</package>
