name: kilted

on:
  pull_request:
    branches:
      - kilted
  push:
    branches:
      - kilted
  schedule:
      - cron: '0 0 * * 6'     
jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@v4
        with:
          ref: kilted
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: yaets
          target-ros2-distro: kilted
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
          # yml: ./codecov.yml
          fail_ci_if_error: false
